### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by gep13** [huafu/hubot-gitter2#1]
Hello,

I have been trying to get hubot running, using your extension, for my Gitter Room over at [chocolatey/choco](https://gitter.im/chocolatey/choco).  I have been able to successfully deploy hubot onto Azure by using the instructions listed here:

https://github.com/scrumdod/hubot-vsonline/blob/master/docs/HOWTO-HubotForVisualStudioOnlineTeamRoomsOnAzureWebSite.md

And you can see it is alive here:

![image](https://cloud.githubusercontent.com/assets/1271146/5882639/28b6b102-a343-11e4-9ac0-f955219f07c1.png)

However, it doesn't seem to be responding to any commands, i.e. `hubot ping` comes back with nothing.  Are you able to suggest anything that I can try to get this working?  Thanks in advance!

Gary

**Comment by gep13** [comment]
I have decided to not deploy to Azure after a recommendation from the author of the linked article to not do it there (due to lack of use of Webhooks):

https://twitter.com/tspascoal/status/558735889871171584

Instead, I have now deployed the application to heroku, but I still don't seem to be able to get it working.  I can see in the Heroku logs that something is happening, but I am never getting a response from the bot in the chat room.  Can you offer any suggestions as to how to debug this?

Thanks

**Comment by huafu** [comment]
Hi Gary, it's 5am here so I'll look into your problem more in details in a few hours. But first of all, are you sure that:
- you created a user and allowed it in your room(s) for the bot on gitter
- you used this user credentials in hubbot config for this plugin (see README)

Anyway before I can check further, be sure that you followed all readme instructions of course ;-)

**Comment by gep13** [comment]
Hello,

Thanks for taking the time to reply to me, I really appreciate it!

Yes, I have been through all the readme instructions, but some of them don't quite work anymore, as some hubot commands have been deprecated.  I have found the alternatives though, and these are the commands that I have used to setup the hubot instance in heroku:

```
heroku login
cd C:\heroku
mkdir chocobot
cd .\chocobot
yo hubot
npm install --save hubot-gitter2
git init
git add .
git commit -m "Initial commit"
heroku create
heroku config:set HUBOT_GITTER2_TOKEN=****
heroku config:set HEROKU_URL=https://whispering-peak-2284.herokuapp.com
heroku config:set HUBOT_GITTER2_TESTING_ROOMS=chocolatey/choco
git push heroku master
heroku logs
```

Where `***` is the Gitter personal access token for the user that I am signed into the Gitter Chat Room as.  During the `yo hubot` step, I chose `chocobot` as the name, and `gitter2` as the adapter name.

I have logged into the chat room as the choco-bot user, which you can see here:

![image](https://cloud.githubusercontent.com/assets/1271146/5890974/fce56fbc-a470-11e4-8801-37d58532bc77.png)

If I use the `heroku logs` command, I can see that there is some output from your adapter:

![image](https://cloud.githubusercontent.com/assets/1271146/5890975/1b0b13d4-a471-11e4-97db-9be2b5fbae77.png)

And if I go into the chat room and try to do something like either `hubot ping` or chocobot ping``` I don't get anything back, but I can see that there are some additional log statements made by the adapter, so I know it is doing "something" but it just doesn't seem to make any posts into the chat room:

![image](https://cloud.githubusercontent.com/assets/1271146/5888452/1313a526-a3f7-11e4-9d6a-b4906b89152f.png)

Any ideas!

**Comment by gep13** [comment]
UPDATE:

Ok, scratch all of the above :smile_cat: 

I have just ran through all of these steps again this morning, and I am happy to say that it is now working:

![image](https://cloud.githubusercontent.com/assets/1271146/5890979/96fa7066-a471-11e4-9042-b1db63b4e984.png)

No idea what I have done differently this morning, but it is now working!

Thanks again!
