### ISSUE TITLE
Are you planning a new release?

### ISSUE THREAD

**Issue by gep13** [huafu/hubot-gitter2#18]
@huafu I was just wondering if you were planning on generating a new release soon?

There is at least one fix on the develop branch that we would like to see pushed as a new release, as it allows us to run this Hubot Gitter on Azure.  Thanks in advance!

**Comment by huafu** [comment]
I have to say the true, it is so long I did not work on this.... can't remember what implies a new release ;-)
So I'll now digg in that :-D

**Comment by gep13** [comment]
@huafu that is great news! I wish I could help, but I haven't really dealt with npm packages before.  Happy to test something out once you have something ready though.  Thanks!

**Comment by huafu** [comment]
Oh! Your message now actually reminds me how to do (well, more likely what
to do haha). I am on my phone now but I'll try to do this next time I'm on
my computer

**Comment by mose** [comment]
We really need a new release, the currently available npm package v0.1.3 is broken (and fixed only on https://github.com/huafu/hubot-gitter2/commit/723a7764c6f642f1d4bc4de941fed39bd15b049f). If you need any help in publishing, I can help.

**Comment by davidchambers** [comment]
I've opened #27 to make your life easier, @huafu. Here's the plan:

1.  Merge #27.
2.  Merge `master` into `develop`. `develop` should at all times be a superset of `master`.
3.  Pull from `develop` into `master`, so both point to the same commit (the merge commit for #27). This will be a fast forward.
4.  Run `npm run release minor` (while on `master`).
5.  Pull from `master` into `develop`. This will be a fast forward, and will ensure that `develop` remains a superset of `master`.
6.  Consider simplifying the branching strategy. ;)

The last step is optional, and a bit cheeky! In my experience having "stable" and "development" branches is more trouble than it's worth, but you may have good reasons for having separate branches for this repository.

Let me know if I can provide further assistance. If you like, @huafu, you could add me as a contributor and I could take care of all these steps (except the last one, which is obviously your call). I realize I'm a complete stranger, but I hope my GitHub profile indicates that I have good intentions. I'm just doing what I can to move this issue forward after one year. :)

**Comment by huafu** [comment]
@davidchambers and @mose I am going to add you as a contributors, I am in need of some help here.
I actually prepared a release in `release/0.2.0` with updated package versions (and the use of `yarn`), but I wanted to test it before publishing... can't remember how to test, and no time to investigate now... I did not even use CoffeeScript since 2+ years I think (but that is not actually the issue).

Closing this for now, I guess adding you guys will solve this issue.

**Comment by mose** [comment]
Okay, I will try to give it a go asap and feedback about it.

**Comment by huafu** [comment]
Thanks!

**Comment by davidchambers** [comment]
I'm preparing a new xyz release. I'll then update #27 at which point we can easily release a new version of this package.

In addition to adding us as contributors, @huafu, could you add us as package owners?

```console
$ npm owner add davidchambers hubot-gitter2
$ npm owner add mose hubot-gitter2
```

**Comment by huafu** [comment]
@davidchambers done, sorry again for my bad reactivity...

**Comment by davidchambers** [comment]
Thanks, @huafu!

**Comment by davidchambers** [comment]
[Version 1.0.0][1] is now available. :tada:


[1]: https://github.com/huafu/hubot-gitter2/releases/v1.0.0

**Comment by gep13** [comment]
@davidchambers this is great news!  Thank you for the update!
