### ISSUE TITLE
User can't operate the bot

### ISSUE THREAD

**Issue by sils** [huafu/hubot-gitter2#23]
We have a user on gitter who can't operate the bot - it seems that there's some kind of user limit somewhere which is 100 users? Channels go easily beyond that :/

**Comment by sils** [comment]
CC @chauffer

**Comment by sils** [comment]
:point_up: [September 6, 2016 9:23 PM](https://gitter.im/coala-analyzer/coala?at=57cf17a41baa312a6bdc1f63)

**Comment by sils** [comment]
as an example

**Comment by MadLittleMods** [comment]
@sils1297 You are probably running into the max of the `limit` parameter which is 100 on `/v1/rooms/:roomId/users`

You need to page through the rest of the members via `skip`, see https://developer.gitter.im/docs/rooms-resource#users

**Comment by sils** [comment]
That sounds like something the adapter should do. Why does it need to know the users in order to respond to them?

**Comment by sils** [comment]
Hey, this is really annoying to us. Is this adapter maintained?

**Comment by sils** [comment]
@nemaniarjun maybe we should make a permanent fork then, hubot-gitter3 or so

**Comment by NickSeagull** [comment]
@sils any updates on this?

**Comment by sils** [comment]
@NickSeagull I think we're still using our fork - @meetmangukiya?

**Comment by NickSeagull** [comment]
Could I use it? I have a room with 260 users and this one seems to choke on them 🙃 @sils

**Comment by meetmangukiya** [comment]
@sils we have ditched this for more than 4 months now I think.
 
@NickSeagull we had been using https://www.npmjs.com/package/hubot-gitter2-patched as the fixed one, maybe you should try it out :) . @nemaniarjun had patched it

**Comment by meetmangukiya** [comment]
This was our config file : https://gitlab.com/coala/cobot/blob/master/package.json and this is also the repository of the hubot instance that we used to use earlier if this is any help

**Comment by NickSeagull** [comment]
Great thanks @meetmangukiya :)

**Comment by meetmangukiya** [comment]
This was our config file : https://gitlab.com/coala/cobot/blob/master/package.json and this is also the repository of the hubot instance that we used to use earlier if this is any help

**Comment by sils** [comment]
ah right we switched to corobo ^^
