### ISSUE TITLE
organizing previous releases

### ISSUE THREAD

**Issue by davidchambers** [huafu/hubot-gitter2#30]
The current state of this project confuses me: some releases available via npm are not tagged on GitHub, some GitHub version tags do not correspond to npm releases, and there's at least one *untagged* commit which updates the `version` field of __package.json__.

```console
$ npm view hubot-gitter2 versions --json
[
  "0.0.1",
  "0.0.2",
  "0.0.3",
  "0.1.0",
  "0.1.2",
  "0.1.3"
]
```

```console
$ git ls-remote --tags git@github.com:huafu/hubot-gitter2.git
70b6211845ebf020a809baa9279d6d8b468f1946	refs/tags/0.1.0
4dbb3827fbdcbbdd63b43d133b792930e837913a	refs/tags/0.1.0^{}
feba856a76fa3f2e17646bc53e5dc3cc53b5df9b	refs/tags/0.1.1
66c6c5726e26aadb1f8b8a0ec6ba8ab3dbe73d60	refs/tags/0.1.1^{}
3a429a9b3e7dab06272e541614506c135ea89cda	refs/tags/0.1.2
beef873224a8d5677420d50ca7783656eab3d5fc	refs/tags/0.1.2^{}
8ca526698e098cf608f9456bf3ad4390f5c81652	refs/tags/0.1.3
18d5d0da398d3a69941e5c28e094d5debbf0d27a	refs/tags/0.1.3^{}
```

I'd like to reconcile these differences before publishing a new release.

@huafu, I have two questions for you:

1. Are you happy for me to create annotated tags for untagged commits which correspond to npm releases?
2. Are you happy for me to ignore the [`release/0.2.0`][1] branch, since the “release” commit was not tagged and the version was not published to the npm registry?

[1]: https://github.com/huafu/hubot-gitter2/tree/release/0.2.0

**Comment by huafu** [comment]
1. yeah no problem
2. I'd rather have `release/0.2.0` renamed to `features/unpublished-wip-0.2.0` so that I do not forget it and take some time to look at what's there later

Thanks man for taking care of this BTW!

**Comment by davidchambers** [comment]
I have created an annotated tag for each version (including those never published to npm):

```console
$ git ls-remote --tags git@github.com:huafu/hubot-gitter2.git
70b6211845ebf020a809baa9279d6d8b468f1946	refs/tags/0.1.0
4dbb3827fbdcbbdd63b43d133b792930e837913a	refs/tags/0.1.0^{}
feba856a76fa3f2e17646bc53e5dc3cc53b5df9b	refs/tags/0.1.1
66c6c5726e26aadb1f8b8a0ec6ba8ab3dbe73d60	refs/tags/0.1.1^{}
3a429a9b3e7dab06272e541614506c135ea89cda	refs/tags/0.1.2
beef873224a8d5677420d50ca7783656eab3d5fc	refs/tags/0.1.2^{}
8ca526698e098cf608f9456bf3ad4390f5c81652	refs/tags/0.1.3
18d5d0da398d3a69941e5c28e094d5debbf0d27a	refs/tags/0.1.3^{}
0f71876f8bfac1454932baf40e6f3c14aed803de	refs/tags/v0.0.1
782813734baaa60fffaed474e4b241cd45b273fc	refs/tags/v0.0.1^{}
6906cbc4ec6dc623688d214188179ba3be9d5a98	refs/tags/v0.0.2
22dc60f4a205eb9c6fe99252bba23fe0650579fd	refs/tags/v0.0.2^{}
a329ebcaf7fe2e6e41c9c3c6aac52b16d64799d0	refs/tags/v0.0.3
1f25c8d88249815d651c7ce737058c9a6bd1361f	refs/tags/v0.0.3^{}
1a8d97a1061f280a758e93bb85429a2d3b51273a	refs/tags/v0.1.0
4dbb3827fbdcbbdd63b43d133b792930e837913a	refs/tags/v0.1.0^{}
d63b5764ec9ac94a3e808d06ffe8b19623d1379a	refs/tags/v0.1.1
66c6c5726e26aadb1f8b8a0ec6ba8ab3dbe73d60	refs/tags/v0.1.1^{}
f482d4725cacb6e9c6b9fce87b4b0caf62322944	refs/tags/v0.1.2
beef873224a8d5677420d50ca7783656eab3d5fc	refs/tags/v0.1.2^{}
43e104900b40bdf33a80076486ebf6ce838e85b6	refs/tags/v0.1.3
18d5d0da398d3a69941e5c28e094d5debbf0d27a	refs/tags/v0.1.3^{}
```

> I'd rather have `release/0.2.0` renamed to `features/unpublished-wip-0.2.0` so that I do not forget it and take some time to look at what's there later

I renamed the branch as you requested. :)
