### ISSUE TITLE
move release notes from readme to /releases

### ISSUE THREAD

**Issue by davidchambers** [huafu/hubot-gitter2#32]
We will soon merge #27, at which point I'll release a new version of this package. With this in mind, I propose moving the release notes from the readme to their respective [releases][1]. This would reduce the release process to just two steps:

1.  Run `npm run release [major|minor|patch]`.
2.  Create a GitHub release for the tag created in the previous step.

If this change is okay with you, @huafu, I will update the three releases in question then open a pull request to remove the release notes from the readme.

[1]: https://github.com/huafu/hubot-gitter2/releases

**Comment by huafu** [comment]
@davidchambers thank you very much for asking all those, but we must find a faster way of communicating. That for you to not have to wait for my replies all the time. My Skype ID is `pedroleouf` maybe we can chat over there of simple questions like this one.

Anyway, for your question here, all good ;-)
